# Generated by Django 5.1.5 on 2025-01-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herosection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminHOD',
        ),
    ]
