# Generated by Django 5.1.5 on 2025-01-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herosection', '0002_rename_admin_adminhod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhod',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminhod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adminhod',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='password',
        ),
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='password',
        ),
    ]
