# Generated by Django 5.1.5 on 2025-02-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herosection', '0002_alter_sessionyearmodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
