# Generated by Django 5.1.5 on 2025-02-12 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herosection', '0003_alter_leavereportstaff_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herosection.staffs'),
        ),
    ]
