# Generated by Django 5.1.5 on 2025-01-31 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herosection', '0003_remove_adminhod_email_remove_adminhod_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='herosection.courses'),
        ),
    ]
