# Generated by Django 5.1.5 on 2025-03-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herosection', '0004_alter_leavereportstaff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(),
        ),
    ]
